### ISSUE TITLE
Cannot load byebug when creating a new collection

### ISSUE THREAD

**Issue by haukurhrafn** [openjaf/cenit_cmd#13]
When I try to build a new collection I get the following error:
```
Haukurs-MacBook-Pro:cenit-collections Haukur$ cenit collection ecommerce_to_odoo --source=file.json
/Users/Haukur/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- byebug (LoadError)
	from /Users/Haukur/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/Haukur/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cenit_cmd-0.0.6/lib/cenit_cmd/collection.rb:1:in `<top (required)>'
	from /Users/Haukur/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/Haukur/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/Haukur/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cenit_cmd-0.0.6/lib/cenit_cmd.rb:9:in `<top (required)>'
	from /Users/Haukur/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/Haukur/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/Haukur/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cenit_cmd-0.0.6/bin/cenit:2:in `<top (required)>'
	from /Users/Haukur/.rbenv/versions/2.1.2/bin/cenit:23:in `load'
	from /Users/Haukur/.rbenv/versions/2.1.2/bin/cenit:23:in `<main>'
```

**Comment by sanchojaf** [comment]
Hi @haukurhrafn,  Which was the content of file.json?
